### ISSUE TITLE
Error with lola.psf

### ISSUE THREAD

**Issue by NilsBe** [robey/font-problems#1]
First of all thanks a lot for the fonts. I tried them out with a 1.8 Inch (160x128px) TFT Display connected to a Raspberry Pi Zero W. 

tom-thumb-256.psf and oranj.psf are fantastic as there is hardly space and the existing fonts were all too large. 

I only have to report that I get this error when I try to set the Font lola.psf:

pi@raspberrypi:~ $ sudo setfont -C /dev/console lola.psf
putfont: KDFONTOP: Invalid argument

Again, Thank you!

**Comment by robey** [comment]
oh, i think i see why... the psf file gives a char width of 6 pixels. many linux consoles can only do 8-pixel widths in vga mode.

it's a proportional font anyway, so i'm not sure why i made a psf file. :) i'll delete it.
